#!/usr/bin/env python3
"""
Main file for dealing with connecting to MakeMKV and handling errors

Reference:
- https://www.makemkv.com/developers/usage.txt
- https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/MakeMKV-Codes
"""

import collections
import dataclasses
import enum
import itertools
import logging
import os
import re
import shlex
import shutil
import signal
import subprocess
from time import monotonic, sleep, time

import arm.config.config as cfg
from arm.models import SystemDrives, Track
from arm.models.job import MANUAL_START_SIGNAL, Job, JobState
from arm.ripper import utils
from arm.ripper.utils import notify
from arm.ui import db

MAKEMKV_INFO_WAIT_TIME = 60  # [s]
"""Wait for concurrent MakeMKV info processes.
This is introduced due to a race condition creating makemkvcon zombies
"""
MAKEMKV_UNKNOWN_DRV = 999
"""Currently the value is always 999"""

MAKEMKV_STREAM_CODE_TYPE_VIDEO = 6201
"""Identifies the stream as a Video stream"""
MAX_DEVICES = 16
"""MakeMKV Optical Devices Limit"""
SOURCE = "MakeMKV"
"""Used as input argument for put_track"""

ERROR_MESSAGE_OPERATION_RESULT = "Internal error - Operation result is incorrect (132)"
ERROR_MESSAGE_TRAY_OPEN = "Scsi error - NOT READY:MEDIUM NOT PRESENT - TRAY OPEN"
ERROR_MESSAGE_MEDIUM_ERROR = "Scsi error - MEDIUM ERROR:L-EC UNCORRECTABLE ERROR"
ERROR_MESSAGE_HARDWARE_ERROR = "Scsi error - HARDWARE ERROR:441E"


class OutputType(enum.Flag):
    """
    MakeMKV Output Types

    The Output Type are the first characters in a stdout line generated by
    makemkvcon before the colon.
    """
    DRV = enum.auto()
    """Drive"""
    MSG = enum.auto()
    """Message"""
    CINFO = enum.auto()
    """Disc Info"""
    SINFO = enum.auto()
    """Stream Info"""
    TCOUNT = enum.auto()
    """Title Count"""
    TINFO = enum.auto()
    """Title Info"""
    PRGV = enum.auto()
    """Progress Bar Value"""
    PRGC = enum.auto()
    """Progress Bar Current Progress on Title"""
    PRGT = enum.auto()
    """Progress Bar Total Progress on Title"""


class DriveVisible(enum.IntEnum):
    """
    Definitions of `DriveInformation.visible` colon of the OutputType.DRV.
    """
    EMPTY = 0
    OPEN = 1
    LOADED = 2
    LOADING = 3
    NOT_ATTACHED = 256

    @classmethod
    def _missing_(cls, value):
        logging.debug(f"Undefined Visible Value {value} in {cls}")
        return cls.NOT_ATTACHED


class DriveType(enum.Enum):
    """
    Definitions of the Drive Type issued by OutputType.DRV
    """
    CD = 0
    DVD = 1
    BD_TYPE1 = 12
    BD_TYPE2 = 28
    """Both 12 and 28 are blu ray drives.
    Note: Not sure what the difference is.
    """

    @classmethod
    def _missing_(cls, value):
        logging.debug(f"Undefined Drive Type {value} in {cls}")
        return cls.CD


class MessageID(enum.IntEnum):
    """
    Known MakeMKV Message Codes
    """

    LIBMKV_TRACE = 1002
    """LIBMKV_TRACE: %1
    - "Exception: Error in p->FetchFrames(1,false)"
    """
    VERSION_INFO = 1005
    """%1 started"""
    GENERIC_INFO = 1011
    """%1"""
    READ_ERROR = 2003
    """Error '%1' occurred while reading '%2' at offset '%3'
    Indicates (mostly non-fatal) Read Error
    """
    WRITE_ERROR = 2019
    """Error '%1' occurred while creating '%2'
    Indicates (mostly fatal) Write Error
    """
    COMPLEX_MULTIPLEX = 3024
    """Complex multiplex encountered
    Usually takes more time to process.
    """
    TITLE_SKIPPED = 3025
    TITLE_ADDED = 3028
    AUDIO_SKIPPED_EMPTY = 3034
    """Audio stream #%1 in title #%2 looks empty and was skipped"""
    SUBTITLE_SKIPPED_IDENTICAL = 3030
    """Subtitle stream #%1 is identical to stream #%2 and was skipped"""
    FILE_ADDED = 3307
    """File %1 was added as title #%2"""
    RIP_TITLE_ERROR = 5003
    """Failed to save title %1 to file %2"""
    RIP_COMPLETED = 5004
    """%1 titles saved, %2 failed"""
    RIP_DISC_OPEN_ERROR = 5010
    """Failed to open disc (mostly fatal)"""
    RIP_SUMMARY_BEFORE = 5014
    """Saving %1 titles into directory %2"""
    RIP_SUMMARY_AFTER = 5037
    """Copy complete. %1 titles saved, %2 failed."""
    EVALUATION_PERIOD_EXPIRED_INFO = 5052
    """Evaluation period has expired.
    Please purchase an activation key if you've found this application useful.
    You may still use all free functionality without any restrictions.
    """
    KEY_EXPIRED = 5073
    """Your temporary key has expired and was removed. Please restart the application.
    The free beta key ARM fetches from the MakeMKV forum (scripts/update_key.sh) is
    only valid for a limited time, usually until the end of the month.
    """
    EVALUATION_PERIOD_EXPIRED_APP_TOO_OLD = 5021
    """This application version is too old.  Please download the latest version
    at http://www.makemkv.com/ or enter a registration key to continue using
    the current version.
    """
    EVALUATION_PERIOD_EXPIRED_SHAREWARE = 5055
    """Evaluation period has expired, shareware functionality unavailable."""

    RIP_BACKUP_FAILED_PRE = 5096
    RIP_BACKUP_FAILED = 5080
    """Backup Mode Failed."""


KEY_EXPIRED_CODES = frozenset({MessageID.KEY_EXPIRED, MessageID.EVALUATION_PERIOD_EXPIRED_APP_TOO_OLD})
"""MakeMKV messages meaning it has no valid key (see MakeMkvKeyExpiredError)"""


class StreamID(enum.IntEnum):
    """
    Definition of the Stream ID and its reference to the stored content
    """
    UNKNOWN = 0
    TYPE = 1
    ASPECT = 20
    FPS = 21


class TrackID(enum.IntEnum):
    """
    Definition of the Track ID and its reference to the stored content
    """
    CHAPTERS = 8
    DURATION = 9
    FILESIZE = 11
    FILENAME = 27


@dataclasses.dataclass
class MakeMKVMessage:
    """
    Message output

    `MSG:code,flags,count,message,format,param0,param1,...`
    """
    code: int
    """Unique Message Code"""
    flags: int
    """Message Flags"""
    count: int
    """Number of Parameters"""
    message: str
    """Formatted Message"""
    sprintf: str
    """Unformatted Message"""

    def __post_init__(self):
        self.code = int(self.code)
        self.flags = int(self.flags)
        self.count = int(self.count)


@dataclasses.dataclass
class MakeMKVErrorMessage(MakeMKVMessage):
    """Error Message"""
    error: str

    def __post_init__(self):
        if len(self.sprintf) < 2:
            raise ValueError(self.sprintf)
        self.error = str(self.sprintf[1])
        self.sprintf = self.sprintf[2:]


@dataclasses.dataclass
class Titles:
    """
    Disc information output messages

    `TCOUT:count`
    """
    count: int
    """Titles Count"""

    def __post_init__(self):
        self.count = int(self.count)


@dataclasses.dataclass
class CInfo:
    """
    Disc Information

    `CINFO:id,code,value`
    ```
    """
    id: int  # pylint: disable=C0103
    """Attribute ID, see AP_ItemAttributeId in apdefs.h"""
    code: int
    """Message Code if Attribute Value is a constant string"""
    value: str
    """Attribute Value"""

    def __post_init__(self):
        self.id = int(self.id)
        self.code = int(self.code)


@dataclasses.dataclass
class TInfo(CInfo):
    """
    Title Information

    `TINFO:tid,id,code,value`
    """
    tid: int
    """Title ID"""

    def __post_init__(self):
        super().__post_init__()
        self.tid = int(self.tid)


@dataclasses.dataclass
class SInfo(TInfo):
    """
    Stream Information

    `SINFO:id,code,value`

    """
    sid: int

    def __post_init__(self):
        super().__post_init__()
        self.sid = int(self.sid)


@dataclasses.dataclass
class ProgressBarValues:
    """
    Progress bar values for current and total progress

    PRGV:current,total,max
    """
    current: int
    """current progress value"""
    total: int
    """total progress value"""
    maximum: int
    """maximum possible value for a progress bar, constant"""

    def __post_init__(self):
        self.current = int(self.current)
        self.total = int(self.total)
        self.maximum = int(self.maximum)


@dataclasses.dataclass
class ProgressBarTitle:
    """
    Progress Bar Information
    """
    code: int
    """unique message code"""
    oid: int
    """operation sub-id"""
    name: str
    """name string"""

    def __post_init__(self):
        self.code = int(self.code)
        self.oid = int(self.oid)


@dataclasses.dataclass
class ProgressBarCurrent(ProgressBarTitle):
    """
    Current progress title

    PRGC:code,id,name
    """


@dataclasses.dataclass
class ProgressBarTotal(ProgressBarTitle):
    """
    Total progress title

    PRGT:code,id,name
    """


@dataclasses.dataclass(order=True)
class DriveInformation:
    """
    Basic Optical Drive Information from MakeMKV Drive Scan Messages

    `DRV:index,visible,enabled,flags,drive name,disc name`

    @see arm.ui.settings.DriveUtils.Drive
    """

    mount: str
    """Device Name (sort index, dynamic)"""
    disc: str
    """Media title/label (changes with disc)"""
    info: str
    """Drive Name (changes on FW update)"""
    flags: int
    """Disc Type (persistent)"""
    enabled: bool
    """Unknown Purpose, always True"""
    visible: bool
    """Drive Present"""
    index: int
    """MakeMKV disc index"""

    def __post_init__(self):
        self.flags = int(self.flags)
        self.enabled = bool(int(self.enabled) == MAKEMKV_UNKNOWN_DRV)
        self.visible = int(self.visible)
        self.index = int(self.index)


@dataclasses.dataclass
class Drive(DriveInformation):
    """
    Extended MakeMKV Drive Information (with medium information)
    """
    loaded: bool = dataclasses.field(init=False, default=False)
    """Device has Medium loaded (changes)"""
    open: bool = dataclasses.field(init=False, default=False)
    """Device Tray is open"""
    attached: bool = dataclasses.field(init=False, default=True)
    """Device is attached / available for the system"""
    media_cd: bool = dataclasses.field(init=False, default=False)
    """Medium is CD"""
    media_dvd: bool = dataclasses.field(init=False, default=False)
    """Medium is DVD"""
    media_bd: bool = dataclasses.field(init=False, default=False)
    """Medium is BD"""

    def __post_init__(self):
        super().__post_init__()
        drive_type = DriveType(self.flags)
        if drive_type == DriveType.CD:
            self.media_cd = True
        elif drive_type == DriveType.DVD:
            self.media_dvd = True
        elif drive_type == DriveType.BD_TYPE1:
            self.media_bd = True
        elif drive_type == DriveType.BD_TYPE2:
            self.media_bd = True
        drive_visible = DriveVisible(self.visible)
        if drive_visible == DriveVisible.EMPTY:
            self.loaded = False
        elif drive_visible == DriveVisible.OPEN:
            self.open = True
        elif drive_visible == DriveVisible.LOADED:
            self.loaded = True
        elif drive_visible == DriveVisible.LOADING:
            self.loaded = True
        elif drive_visible == DriveVisible.NOT_ATTACHED:
            self.attached = False


class MakeMkvParserError(ValueError):
    """Exception raised when the stdout line of makemkvcon cannot get parsed."""


class UpdateKeyErrorCodes(enum.IntEnum):
    """
    Definition of the defined exit codes of update_key.sh
    """
    GENERAL_ERROR = 1
    PARSE_ERROR = 20
    """The .MakeMKV/settings.conf file has invalid content."""
    INTERNAL_ERROR = 30
    """The script produced an invalid .MakeMKV/settings.conf."""
    URL_ERROR = 40
    """This Error is raised if the curl command fails"""
    INVALID_MAKEMKV_SERIAL = 50
    """The provided MakeMKV serial should follow a regex M-<serial>."""
    UNDEFINED_ERROR = 256

    @classmethod
    def _missing_(cls, value):
        logging.error(f"An Unknown Error Code happened: {value}")
        return cls.UNDEFINED_ERROR


class UpdateKeyRunTimeError(RuntimeError):
    """
    Exception raised when a update_key.sh fails to update the MakeMKV Serial Key.

    Attributes:
        message: the explanation of the error
    """

    def __init__(self, returncode, cmd, output=None):
        if len(cmd) == 3:
            cmd[2] = cmd[2][:4] + "XXXX"  # don't log the key to cli
        logging.debug(f"Updating Key with command: '{' '.join(cmd)}'")
        if output is not None:
            logging.debug(f"update_key.sh output: {output.splitlines()}")
        error_code = f"{returncode} {UpdateKeyErrorCodes(returncode).name}"
        self.message = f"Error updating MakeMKV key, return code: {error_code}"
        logging.error(self.message)
        super().__init__(self.message)


class MakeMkvRuntimeError(RuntimeError):
    """
    Exception raised when a CalledProcessError is thrown during execution of a
    `makemkvcon` command.

    Attributes:
        message: the explanation of the error
    """

    def __init__(self, returncode, cmd, output=None, stderr=None):
        logging.debug(f"MakeMKV command: '{' '.join(cmd)}'")
        if output is not None:
            logging.debug(f"MakeMKV output: {output}")
        if stderr is not None:
            logging.debug(f"MakeMKV stderr: {stderr}")
        self.message = f"Call to MakeMKV failed with code: {returncode}"
        logging.error(self.message)
        super().__init__(self.message)


def parse_content(content, num_header, num_message):
    """
    Helper Function to parse the MakeMKV Messages

    >>> msg = '1005,0,1,"MakeMKV v1.17.8 linux(x64-release) started","%1 started","MakeMKV v1.17.8 linux(x64-release)"'
    >>> list(parse_content(msg, 3, -1))  # MSG
    ['1005', '0', '1', 'MakeMKV v1.17.8 linux(x64-release) started', '%1 started', 'MakeMKV v1.17.8 linux(x64-release)']
    >>> msg = '0'
    >>> list(parse_content(msg, 0, 0))  # TCOUT
    ['0']
    >>> msg = '6,256,999,0,"BD-Drive","THE TITLE","/dev/sr0"'
    >>> list(parse_content(msg, 4, 2))  # DRV
    ['6', '256', '999', '0', 'BD-Drive', 'THE TITLE', '/dev/sr0']
    >>> msg = '1,6209,"Blu-ray disc"'
    >>> list(parse_content(msg, 2, 0))  # CINFO
    ['1', '6209', 'Blu-ray disc']
    >>> msg = '1,26,0,"155,156,157"'
    >>> list(parse_content(msg, 3, 0))  # TINFO
    ['1', '26', '0', '155,156,157']
    >>> msg = '0,0,28,0,"ger"'
    >>> list(parse_content(msg, 4, 0))  # SINFO
    ['0', '0', '28', '0', 'ger']
    """
    # The header is considered as the first n non-string entries
    header = content.split(",", maxsplit=num_header)
    # (str) messages wrapped in double quotes *may* contain comma
    message = header[-1].split('","', maxsplit=num_message)
    return itertools.chain(header[:-1], (x.strip('"') for x in message))


def parse_line(line):
    """Parse MakeMkv Output Line to DataClasses"""
    if ":" not in line:
        raise MakeMkvParserError("No Message Type Detected")
    msg_type, content = line.split(":", maxsplit=1)
    if msg_type not in OutputType.__members__:
        raise MakeMkvParserError(f"Cannot parse '{msg_type}':'{content}'")
    msg_type = OutputType[msg_type]
    if msg_type == OutputType.MSG:
        temp = parse_content(content, 3, -1)
        data = MakeMKVMessage(*itertools.islice(temp, 4), list(temp))
        message = MakeMKVOutputChecker(data).check()
    elif msg_type == OutputType.PRGV:
        message = ProgressBarValues(*parse_content(content, 2, 0))
    elif msg_type == OutputType.PRGC:
        message = ProgressBarCurrent(*parse_content(content, 2, 0))
    elif msg_type == OutputType.PRGT:
        message = ProgressBarTotal(*parse_content(content, 2, 0))
    elif msg_type == OutputType.SINFO:
        tid, sid, *info = parse_content(content, 4, 0)
        message = SInfo(*info, tid, sid)
    elif msg_type == OutputType.TINFO:
        tid, *info = parse_content(content, 3, 0)
        message = TInfo(*info, tid)
    elif msg_type == OutputType.CINFO:
        message = CInfo(*parse_content(content, 2, 0))
    elif msg_type == OutputType.DRV:
        message = Drive(*reversed(list(parse_content(content, 4, 2))))
    elif msg_type == OutputType.TCOUNT:
        message = Titles(*parse_content(content, 0, 0))
    else:
        raise MakeMkvParserError(f"Cannot handle '{msg_type}':'{content}'")
    return msg_type, message


def makemkv_info(job, select=None, index=9999, options=None):
    """
    Use MakeMKV info to search the system for optical drives

    Parameters:
        job: arm.models.job.Job
        select (OutputType): Message Type (default: all)
        index: Makemkv disc index (default: all)
        options: Additional options to be passed to makemkvcon (default: [])
    Yields:
        dataclasses of selected type:
            - Message
            - Titles
            - CInfo
            - TInfo
            - SInfo

    ```
    $ makemkvcon -r info disc:9999
    MSG:1005,0,1,"MakeMKV v1.17.8 linux(x64-release) started","%1 started","MakeMKV v1.17.8 linux(x64-release)"
    DRV:0,1,999,0,"BD-RE PIONEER BD-RW   BDR-UD04 1.14 BCDL000001WL","","/dev/sr2"
    DRV:1,1,999,0,"BD-RE PIONEER BD-RW   BDR-UD04 1.14 BCDL000002WL","","/dev/sr0"
    DRV:2,1,999,0,"BD-RE PIONEER BD-RW   BDR-UD04 1.14 BCDL000003WL","","/dev/sr3"
    DRV:3,1,999,0,"BD-RE PIONEER BD-RW   BDR-UD04 1.14 BCDL000004WL","","/dev/sr5"
    DRV:4,1,999,0,"BD-RE PIONEER BD-RW   BDR-UD04 1.14 BCDL000005WL","","/dev/sr4"
    DRV:5,1,999,0,"BD-RE PIONEER BD-RW   BDR-UD04 1.14 BCDL000006WL","","/dev/sr1"
    DRV:6,256,999,0,"","",""
    DRV:7,256,999,0,"","",""
    DRV:8,256,999,0,"","",""
    DRV:9,256,999,0,"","",""
    DRV:10,256,999,0,"","",""
    DRV:11,256,999,0,"","",""
    DRV:12,256,999,0,"","",""
    DRV:13,256,999,0,"","",""
    DRV:14,256,999,0,"","",""
    DRV:15,256,999,0,"","",""
    MSG:5010,0,0,"Failed to open disc","Failed to open disc"
    TCOUNT:0
    ```
    """
    if select is None:
        select = OutputType.MSG | OutputType.TCOUNT | OutputType.DRV
    if options is None:
        options = []
    if not isinstance(options, list):
        raise TypeError(options)
    # 1MB cache size to get info on the specified disc(s)
    info_options = ["info", "--cache=1"] + options + [f"disc:{index:d}", f"--minlength={utils.min_length_for(job)}"]
    wait_time = job.config.MANUAL_WAIT_TIME
    max_processes = cfg.arm_config["MAX_CONCURRENT_MAKEMKVINFO"]
    # Put the job back in whatever state it was in before - e.g. still "ripping" for the
    # rescan a rip does, but not for a manual mode scan that is about to wait for the user
    previous_status = job.status
    job.status = JobState.VIDEO_WAITING.value
    db.session.commit()
    utils.sleep_check_process("makemkvcon", max_processes, sleep=(10, wait_time, 10))
    job.status = JobState.VIDEO_INFO.value
    db.session.commit()
    try:
        yield from run(info_options, select)
    finally:
        logging.info("MakeMKV info exits.")
        # The cooldown only exists for other jobs queued behind this one - when this is the
        # only job there is nobody to give a turn to, so don't hold it up (or report it as
        # waiting for a slot)
        if max_processes and other_jobs_active(job):
            job.status = JobState.VIDEO_WAITING.value
            db.session.commit()
            logging.info(f"Penalty {wait_time}s")
            # makemkvcon info tends to crash makemkvcon backup|mkv
            # give other processes time to use this function.
            sleep(wait_time)
            # sleep here until all processes finish (hopefully)
            utils.sleep_check_process("makemkvcon", max_processes, sleep=wait_time)
        job.status = previous_status
        db.session.commit()


def other_jobs_active(job):
    """
    Is any other job still unfinished? Those are the ones that may be waiting for
    their own turn to run makemkvcon

    Parameters:
        job: arm.models.job.Job
    Returns:
        bool
    """
    return db.session.query(Job.job_id).filter(~Job.finished, Job.job_id != job.job_id).first() is not None


def get_drives(job):
    """Get information for all active optical drives

    Parameters:
        job: arm.models.job.Job
    """
    for drive in makemkv_info(job, select=OutputType.DRV):
        if drive.attached:
            yield drive


def makemkv_backup(job, rawpath):
    """
    Rip BluRay with Backup Method

    Parameters:
        job: arm.models.job.Job
        rawpath:
    """
    # backup method
    cmd = [
        "backup",
        "--decrypt",
    ]
    cmd += shlex.split(job.config.MKV_ARGS)
    cmd += [
        f"--minlength={utils.min_length_for(job)}",
        f"--progress={progress_log(job)}",
        f"disc:{job.drive.mdisc:d}",
        rawpath,
    ]
    logging.info("Backing up disc")
    collections.deque(run(cmd, OutputType.MSG), maxlen=0)


def makemkv_mkv(job, rawpath, source=None, rescan=True):
    """
    Rip Blu-ray without enhanced protection or dvd disc

    Parameters:
        job: arm.models.job.Job
        rawpath:
        source: MakeMKV source spec, e.g. "dev:/dev/sr0" or "iso:/path/to.iso".
            Defaults to the job's own optical drive (``dev:{job.devpath}``) -
            pass an ``iso:`` spec to rip from a ddrescue'd image instead (see
            arm/ripper/rip_iso.py).
        rescan: Whether to re-run MakeMKV's disc info scan (get_track_info).
            Only meaningful with the default ``dev:`` source - a retry from
            an already-known-good ISO (source given, rescan=False) reuses
            job.tracks and the track.process selections from the original
            scan instead of re-querying the (possibly still-unreadable)
            physical disc.
    """
    if source is None:
        source = f"dev:{job.devpath}"
    # Manual mode jobs were already scanned, and had their tracks picked by the
    # user, up front - see manual_select_tracks()
    if rescan and not job.manual_start:
        # Get track info form mkv rip
        get_track_info(job.drive.mdisc, job)
    # route to ripping functions.
    if job.manual_start:
        logging.info("Ripping the tracks selected in manual mode")
        process_single_tracks(job, rawpath, 'manual', source=source)
    elif job.config.MAINFEATURE:
        logging.info("Trying to find mainfeature (sorting by chapters desc, filesize desc, track_number asc)")
        track = Track.query.filter_by(job_id=job.job_id).order_by(
            Track.chapters.desc(), Track.filesize.desc(), Track.track_number.asc()).first()
        rip_mainfeature(job, track, rawpath, source=source)
    # if no maximum length, process the whole disc in one command - only on the
    # original scan (rescan=True); a retry (rescan=False) must stick to the
    # already-decided track.process selections via the 'retry' branch below,
    # not re-derive "rip everything" just because mainfeature didn't apply.
    elif rescan and int(job.config.MAXLENGTH) > 99998:
        cmd = [
            "mkv",
        ]
        cmd += shlex.split(job.config.MKV_ARGS)
        cmd += [
            f"--progress={progress_log(job)}",
            source,
            "all",
            rawpath,
            f"--minlength={utils.min_length_for(job)}",
        ]
        logging.info("Process all tracks from disc.")
        collections.deque(run(cmd, OutputType.MSG), maxlen=0)
    elif rescan:
        process_single_tracks(job, rawpath, 'auto', source=source)
    else:
        # No live drive-mode/manual-wait to consult - reuse the track.process
        # selections already persisted by the original scan/manual selection.
        process_single_tracks(job, rawpath, 'retry', source=source)


def set_disc_index(job):
    """
    Make sure job.drive.mdisc holds MakeMKV's disc number for the job's drive,
    querying MakeMKV for it (and storing every drive's number) if not known yet

    Parameters:
        job: arm.models.job.Job
    """
    # Fix: Check if job.drive is None before accessing job.drive.mdisc
    if job.drive is None or job.drive.mdisc is None:
        logging.debug("Storing new MakeMKV disc numbers to database.")
        disc_index = None
        with db.session.no_autoflush:
            for drive in get_drives(job):
                for db_drive in SystemDrives.query.filter_by(mount=drive.mount).all():
                    db_drive.mdisc = drive.index
                    db.session.add(db_drive)
                    # Track disc index for current job's device
                    if drive.mount == job.devpath:
                        disc_index = drive.index
        db.session.commit()
        # Refresh job to get updated drive relationship
        db.session.refresh(job)
        # If job.drive is still None after refresh, log warning with available info
        if job.drive is None:
            if disc_index is not None:
                logging.warning(f"job.drive is None but found disc index {disc_index} for {job.devpath}")
            else:
                logging.error(f"Could not find drive for {job.devpath}")
                raise ValueError(f"No drive found for device {job.devpath}")


def makemkv(job):
    """
    Rip Blu-rays/DVDs with MakeMKV

    Parameters:
        job: arm.models.job.Job
    Returns:
        str: path to ripped files.
    """
    # confirm MKV is working, beta key hasn't expired
    prep_mkv()
    logging.info(f"Starting MakeMKV rip. Method is {job.config.RIPMETHOD}")
    set_disc_index(job)
    logging.info(f"MakeMKV disc number: {job.drive.mdisc:d}")
    # get filesystem in order
    rawpath = setup_rawpath(job, os.path.join(str(job.config.RAW_PATH), str(job.title)))
    logging.info(f"Processing files to: {rawpath}")
    # Rip BluRay
    if (job.config.RIPMETHOD in ("backup", "backup_dvd")) and job.disctype == "bluray":
        makemkv_backup(job, rawpath)
    # Rip BluRay or DVD
    elif job.config.RIPMETHOD == "mkv" or job.disctype == "dvd":
        makemkv_mkv(job, rawpath)
    else:
        logging.info("I'm confused what to do....  Passing on MakeMKV")
    job.eject()
    logging.info(f"Exiting MakeMKV processing with return value of: {rawpath}")
    return rawpath


def rip_mainfeature(job, track, rawpath, source=None):
    """
    Find and rip only the main feature when using Blu-rays

    Parameters:
        job: arm.models.job.Job
        track: arm.models.track.Track
        source: MakeMKV source spec (default: ``dev:{job.devpath}``) - see makemkv_mkv()
    """
    if source is None:
        source = f"dev:{job.devpath}"
    logging.info(f"Processing track#{track.track_number} as mainfeature. Length is {track.length}s")
    filepathname = os.path.join(rawpath, track.filename)
    logging.info(f"Ripping track#{track.track_number} to {shlex.quote(filepathname)}")
    cmd = [
        "mkv",
    ]
    cmd += shlex.split(job.config.MKV_ARGS)
    cmd += [
        f"--progress={progress_log(job)}",
        source,
        track.track_number,
        rawpath,
        f"--minlength={utils.min_length_for(job)}",
    ]
    logging.info("Ripping main feature")
    # Possibly update db to say track was ripped
    collections.deque(run(cmd, OutputType.MSG), maxlen=0)


def process_single_tracks(job, rawpath, mode: str, source=None):
    """
    Process single tracks by MakeMKV one at a time

    Parameters:
        job: arm.models.job.Job
        rawpath:
        mode: 'auto' recomputes each track.process from length thresholds;
            any other value (e.g. 'manual', 'retry') reuses whatever
            track.process is already persisted.
        source: MakeMKV source spec (default: ``dev:{job.devpath}``) - see makemkv_mkv()
    """
    if source is None:
        source = f"dev:{job.devpath}"
    # process one track at a time based on track length
    if mode == 'auto':
        # Process single track automatically based on start and finish times
        for track in job.tracks:
            if track.length < int(utils.min_length_for(job)):
                # too short
                logging.info(f"Track #{track.track_number} of {job.no_of_titles}. Length ({track.length}) "
                             f"is less than minimum length ({utils.min_length_for(job)}).  Skipping")
                track.process = False

            elif track.length > int(job.config.MAXLENGTH):
                # too long
                logging.info(f"Track #{track.track_number} of {job.no_of_titles}. "
                             f"Length ({track.length}) is greater than maximum length ({job.config.MAXLENGTH}).  "
                             "Skipping")
                track.process = False
            else:
                # track is just right
                track.process = True

    # Rip the track if the user has set it to rip, or in auto mode and the time is good

    tracks_to_process = [track for track in job.tracks if track.process]
    process_index = 1
    for track in tracks_to_process:
        logging.info(f"Processing track #{process_index} of {len(tracks_to_process)}. "
                     f"Length is {track.length} seconds.")
        filepathname = os.path.join(rawpath, track.filename)
        logging.info(f"Ripping title {track.track_number} to {shlex.quote(filepathname)}")
        logfile_base = progress_log(job)
        cmd = [
            "mkv",
        ]
        cmd += shlex.split(job.config.MKV_ARGS)
        cmd += [
            f"--minlength={utils.min_length_for(job)}",
            f"--progress={logfile_base}",
            source,
            track.track_number,
            rawpath,
        ]
        # Create a batch info file so the web gui can know when this process started, which track, and how many tracks
        logging.debug(f"Saving batch position info for job {job.job_id}: "
                      f"BINF:{int(time())},{process_index},{len(tracks_to_process)},0000"
                      )
        batch_info_file = logfile_base+".batchinfo"
        if not os.path.exists(batch_info_file):
            with open(batch_info_file, 'w') as f:
                f.write(f"BINF:{int(time())},{process_index},{len(tracks_to_process)},0000")
        else:
            with open(batch_info_file, 'a') as f:
                f.write(f"\nBINF:{int(time())},{process_index},{len(tracks_to_process)},0000")

        logging.debug("Starting to rip single track.")
        collections.deque(run(cmd, OutputType.MSG), maxlen=0)
        process_index += 1


def setup_rawpath(job, raw_path):
    """
    Checks if we need to create path and does so if needed\n\n

    Parameters:
        job: arm.models.job.Job
        raw_path
    Returns:
        str: modified path
    """

    logging.info(f"Destination is {raw_path}")
    base_path = raw_path
    attempt = 0
    while True:
        try:
            os.makedirs(raw_path)
            return raw_path
        except FileExistsError:
            # job.stage is a free-text UI progress string (e.g. "Preparing" or
            # "Track 3/1<br>Analyzing seamless segments") that gets overwritten
            # throughout the job's life - never use it as a path disambiguator.
            # job.job_id is stable and filesystem-safe. Keep incrementing in case
            # an earlier retry of this same job already left a directory behind
            # at that name too.
            attempt += 1
            suffix = str(job.job_id) if attempt == 1 else f"{job.job_id}_{attempt}"
            raw_path = f"{base_path}_{suffix}"
            logging.info(f"{base_path} exists.  Trying {raw_path}")
        except OSError as os_error:
            err = f"Couldn't create the base file path: {raw_path}. Probably a permissions error"
            logging.error(err)
            raise OSError(err) from os_error


def prep_mkv():
    """
    Make sure the MakeMKV key is up-to-date

    Raises:
        UpdateKeyRunTimeError
    """
    cmd = [
        shutil.which("bash") or "/bin/bash",
        os.path.join(cfg.arm_config["INSTALLPATH"], "scripts/update_key.sh"),
    ]
    # if MAKEMKV_PERMA_KEY is populated, use it directly - no need to fetch the beta key,
    # so the network-specific fallback handling below doesn't apply here
    if cfg.arm_config['MAKEMKV_PERMA_KEY'] is not None and cfg.arm_config['MAKEMKV_PERMA_KEY'] != "":
        logging.debug("MAKEMKV_PERMA_KEY populated, using that...")
        # add MAKEMKV_PERMA_KEY as an argument to the command
        cmd += [cfg.arm_config['MAKEMKV_PERMA_KEY']]
        try:
            logging.info("Updating MakeMKV key...")
            proc = subprocess.run(cmd, capture_output=True, check=True)
            stdout = proc.stdout.decode("utf-8")
            logging.debug(f"Command Output for update_key.sh: {stdout.splitlines()}")
        except subprocess.CalledProcessError as err:
            raise UpdateKeyRunTimeError(err.returncode, cmd, output=err.stdout.decode("utf-8")) from err
        return

    try:
        logging.info("Updating MakeMKV key...")
        proc = subprocess.run(cmd, capture_output=True, check=True)
        stdout = proc.stdout.decode("utf-8")
        logging.debug(f"Command Output for update_key.sh: {stdout.splitlines()}")
    except subprocess.CalledProcessError as err:
        error_code = UpdateKeyErrorCodes(err.returncode)
        # A URL_ERROR means the beta-key scrape source (forum.makemkv.com) was
        # unreachable - a transient network issue, not a problem with the key
        # itself. If we already have a working key on disk from a previous
        # successful update, fall back to it instead of aborting the whole
        # job. See: https://github.com/automatic-ripping-machine/automatic-ripping-machine/issues/1785
        if error_code == UpdateKeyErrorCodes.URL_ERROR and _makemkv_key_present():
            logging.warning(
                "Failed to refresh the MakeMKV key due to a network error while "
                "fetching the current beta key. A key already exists in "
                "settings.conf, so continuing the job with it instead of aborting."
            )
            return
        raise UpdateKeyRunTimeError(err.returncode, cmd, output=err.stdout.decode("utf-8"))


def _makemkv_key_present():
    """
    Check whether settings.conf already contains a MakeMKV key.

    Used by prep_mkv() to decide whether a transient failure to *refresh*
    the key (e.g. the beta-key source site being temporarily unreachable)
    can be safely ignored in favor of the last-known-good key, rather than
    treating it the same as a genuinely invalid/rejected key.
    """
    settings_file = "/home/arm/.MakeMKV/settings.conf"
    try:
        with open(settings_file) as settings:
            contents = settings.read()
    except OSError:
        return False
    return re.search(r'app_Key\s*=\s*"[A-Z]-.+"', contents) is not None


def progress_log(job):
    """
    Retrieve the path to the progress log file

    The file path is expected like this by the frontend.

    ToDo: move to Job() class since this is mainly a db wrapper. Then allow the
          front end to pick up the same method.

    Parameters:
        job: arm.models.job.Job
    Returns:
        str: log file

    """
    logfile = os.path.join(job.config.LOGPATH, "progress", f"{job.job_id:d}.log")
    logging.debug(f"logging progress to '{logfile}'")
    return shlex.quote(logfile)


class TrackInfoProcessor:
    """
    Processes MakeMKV track info messages to update Track class.
    """

    def __init__(self, job, index):
        self.job = job
        self.index = index

        # Initialize track-related state variables
        self.track_id = None
        self.seconds = 0
        self.aspect = ""
        self.fps = 0.0
        self.filename = ""
        self.stream_type = None
        self.chapters = 0
        self.filesize = 0

    def process_messages(self):
        output_types = (
            OutputType.CINFO |
            OutputType.SINFO |
            OutputType.TCOUNT |
            OutputType.TINFO
        )
        options = []  # add relevant options here if needed

        for message in makemkv_info(self.job, select=output_types, index=self.index, options=options):
            self._process_message(message)

        # Add the last track if exists
        self._add_track()

    def _process_message(self, message):
        if isinstance(message, (TInfo, SInfo)):
            self._handle_track_or_stream_info(message)
        elif isinstance(message, Titles):
            self._handle_titles(message)

    def _handle_track_or_stream_info(self, message):
        # Detect new track, add previous one if changed
        if self.track_id is not None and message.tid != self.track_id:
            self._add_track()
        self.track_id = message.tid

        if isinstance(message, SInfo):
            assert message.tid == self.track_id, message
            self._handle_sinfo(message)
        elif isinstance(message, TInfo):
            assert message.tid == self.track_id, message
            self._handle_tinfo(message)

    def _handle_sinfo(self, message):
        if message.id == StreamID.TYPE:
            self.stream_type = message.code
        elif self.stream_type == MAKEMKV_STREAM_CODE_TYPE_VIDEO:
            if message.id == StreamID.ASPECT:
                self.aspect = message.value.strip()
            elif message.id == StreamID.FPS:
                self.fps = float(message.value.split()[0])

    def _handle_tinfo(self, message):
        if message.id == TrackID.FILENAME:
            # Extract filename between quotes
            self.filename = next(iter(message.value.split('"')[1::2]), message.value)
        elif message.id == TrackID.DURATION:
            self.seconds = convert_to_seconds(message.value.strip())
        elif message.id == TrackID.CHAPTERS:
            self.chapters = int(message.value.strip())
        elif message.id == TrackID.FILESIZE:
            self.filesize = int(message.value.strip())

    def _handle_titles(self, message):
        logging.info(f"Found {message.count:d} titles")
        utils.database_updater({"no_of_titles": message.count}, self.job)

    def _add_track(self):
        if self.track_id is None:
            return
        utils.put_track(
            self.job,
            self.track_id,
            self.seconds,
            self.aspect,
            str(self.fps),
            False,
            SOURCE,
            self.filename,
            self.chapters,
            self.filesize
        )
        # Reset track info after adding if needed
        self.seconds = 0
        self.aspect = ""
        self.fps = 0.0
        self.filename = ""
        self.chapters = 0
        self.filesize = 0


def get_track_info(index, job):
    """
    Use MakeMKV to get track info and update Track class

    Parameters:
        index: Makemkv disc index
        job: arm.models.job.Job
    Returns:
        None

    .. note:: For help with MakeMKV codes:
    https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/MakeMKV-Codes
    """
    processor = TrackInfoProcessor(job, index)
    processor.process_messages()


def convert_to_seconds(hms_value):
    """
    Find the title length in track info MakeMKV message

    Parameters:
        hms_value: Time in format H:MM:SS
    Returns:
        int: Time in seconds
    """
    hour, mins, secs = hms_value.split(":")
    return int(hour) * 3600 + int(mins) * 60 + int(secs)


class MakeMKVOutputChecker:
    """
    Check MakeMKV output messages for errors and handle special cases.

    Parameters:
        data (MakeMKVMessage): the message to check.
    """

    READ_ERROR_MAP = {
        ERROR_MESSAGE_OPERATION_RESULT: (logging.critical, 'error possibly fatal, creating zombie processes'),
        ERROR_MESSAGE_TRAY_OPEN: (logging.info, 'error mostly non fatal'),
        ERROR_MESSAGE_MEDIUM_ERROR: (logging.critical, 'error possibly fatal, medium removed during mkv backup'),
        ERROR_MESSAGE_HARDWARE_ERROR: (logging.critical, 'error possibly fatal, medium removed during mkv backup'),
    }

    LOG_ONLY_CODES = {
        MessageID.KEY_EXPIRED: logging.critical,
        MessageID.RIP_DISC_OPEN_ERROR: logging.info,
        MessageID.RIP_TITLE_ERROR: logging.warning,
        MessageID.RIP_COMPLETED: logging.info,
        MessageID.LIBMKV_TRACE: logging.warning,
        MessageID.RIP_BACKUP_FAILED_PRE: logging.warning,
        MessageID.EVALUATION_PERIOD_EXPIRED_INFO: logging.warning,
    }

    SPECIAL_ERROR_CODES = {
        MessageID.EVALUATION_PERIOD_EXPIRED_APP_TOO_OLD,
        MessageID.EVALUATION_PERIOD_EXPIRED_SHAREWARE,
        MessageID.RIP_BACKUP_FAILED,
    }

    def __init__(self, data: MakeMKVMessage):
        if not isinstance(data, MakeMKVMessage):
            raise TypeError(f"Expected MakeMKVMessage, got {type(data)}")
        self.data = data

    def check(self):
        """Dispatch processing based on message code."""
        code = self.data.code

        if code == MessageID.RIP_TITLE_ERROR:
            self.rip_title_error()

        if code == MessageID.RIP_COMPLETED:
            return self.zero_saved_files()

        if code == MessageID.READ_ERROR:
            return self.read_error()

        if code == MessageID.WRITE_ERROR:
            return self.write_error()

        if code in self.SPECIAL_ERROR_CODES:
            return self.special_error_code()

        if code in self.LOG_ONLY_CODES:
            return self.log_only_code()

        # Default case: no action needed
        return self.data

    def zero_saved_files(self):
        """
        Check the MSG and see if we saved no files. Raise MakeMkvRuntimeError if saved files =0
        """
        params = self.data.sprintf[1:]
        saved = int(params[0])  # 0
        logging.debug(self.data)
        if saved == 0:
            logging.critical(self.data.message)
            raise MakeMkvRuntimeError(1, ["RIP_COMPLETED"],
                                      output=f"{saved} titles were saved. See log for more details")

    def rip_title_error(self):
        """
        If a single item fails, raise MakeMkvRuntimeError
        """
        logging.critical(self.data.message)
        raise MakeMkvRuntimeError(1, ["RIP_TITLE_ERROR"],
                                  output=self.data.message)

    def read_error(self):
        error_msg = self.data.sprintf[1]
        log_func, debug_msg = self.READ_ERROR_MAP.get(error_msg, (logging.warning, None))

        if debug_msg:
            logging.debug(debug_msg)

        # Choose message to log — prefer full message if debug_msg exists
        log_message = self.data.message if debug_msg else error_msg
        log_func(log_message)

        return MakeMKVErrorMessage(*dataclasses.astuple(self.data), self.data.message)

    def write_error(self):
        error_msg = self.data.sprintf[1]
        if error_msg == "Posix error - No such file or directory":
            logging.critical(self.data.message)
        else:
            logging.warning(error_msg)

        return MakeMKVErrorMessage(*dataclasses.astuple(self.data), self.data.message)

    def special_error_code(self):
        """These Errors are typically critical"""
        logging.critical(self.data.message)
        return MakeMKVErrorMessage(*dataclasses.astuple(self.data), self.data.message)

    def log_only_code(self):
        log_func = self.LOG_ONLY_CODES[self.data.code]
        log_func(self.data.message)
        return self.data


class MakeMkvKeyExpiredError(MakeMkvRuntimeError):
    """
    `makemkvcon` refused to run because it has no valid registration key.

    MakeMKV reports this as "This application version is too old" whatever the
    version - what has really happened is that the free beta key has expired.
    """

    KEY_EXPIRED_MESSAGE = ("MakeMKV's beta key has expired, so it won't run. Waiting for a new key to be "
                           "posted at https://forum.makemkv.com/forum/viewtopic.php?f=5&t=1053 - ARM picks "
                           "it up automatically, so re-insert the disc once it is up.")

    def __init__(self, returncode, cmd, output=None, stderr=None):
        super().__init__(returncode, cmd, output=output, stderr=stderr)
        self.message = self.KEY_EXPIRED_MESSAGE
        self.args = (self.message,)
        logging.error(self.message)


def run(options, select):
    """
    Run makemkv with input cli options and yield selected messages

    Parameters:
        options (list): makemkvcon cli options
        select (OutputType): output Message Type(s)
    Yields:
        dataclasses of selected type
    Raises:
        MakeMkvKeyExpiredError if makemkvcon fails because its key has expired
        MakeMkvRuntimeError on any other makemkvcon exit code
    """
    if not isinstance(options, (tuple, list)):
        raise TypeError(options)
    if not isinstance(select, OutputType):
        raise TypeError(select)
    # Check makemkvcon path, resolves baremetal unique install issues
    makemkvcon_path = shutil.which("makemkvcon")
    # robot process of makemkvcon with
    cmd = [
        makemkvcon_path,
        "--robot",
        "--messages=-stdout",
    ]
    cmd += list(options)
    buffer = []
    key_expired = False
    logging.debug(f"command: '{' '.join(cmd)}'")
    with subprocess.Popen(cmd, stdout=subprocess.PIPE, text=True) as proc:
        logging.debug(f"PID {proc.pid}: command: '{' '.join(cmd)}'")
        for line in proc.stdout:
            line = line.rstrip(os.linesep)
            logging.debug(line)  # Maybe write the raw output to a separate log
            if proc.returncode:
                buffer.append(line)
                continue
            try:
                msg_type, data = parse_line(line)
            except MakeMkvParserError as err:
                logging.warning(err)
                buffer.append(line)
                continue
            logging.debug(data)
            if getattr(data, "code", None) in KEY_EXPIRED_CODES:
                key_expired = True
            if msg_type in select:
                yield data
    if proc.returncode and key_expired:
        raise MakeMkvKeyExpiredError(proc.returncode, cmd, output=os.linesep.join(buffer))
    if proc.returncode:
        raise MakeMkvRuntimeError(proc.returncode, cmd, output=os.linesep.join(buffer))
    if buffer and proc.returncode:
        logging.warning(f"Cannot parse {len(buffer)} lines: {os.linesep.join(buffer)}")
        raise MakeMkvRuntimeError(proc.returncode, cmd, output=os.linesep.join(buffer))
    logging.info("MakeMKV exits gracefully.")


def manual_select_tracks(job):
    """
    Manual mode: scan the disc's tracks as soon as it's identified, then wait for
    the user to pick the tracks to rip (and fix the title if needed) in the UI.

    Runs before the job's title/output paths are worked out, so a title the user
    sets while we wait is what the rip actually gets saved under.

    Parameters:
        job: arm.models.job.Job

    Raises:
        utils.RipperException: if the user never submits a track selection
    """
    # confirm MKV is working, beta key hasn't expired
    prep_mkv()
    set_disc_index(job)
    logging.info("Manual mode: scanning disc tracks")
    get_track_info(job.drive.mdisc, job)
    utils.database_updater({"status": JobState.MANUAL_WAIT_STARTED.value}, job)

    if not wait_for_manual_start(job):
        title = "ARM is Sad - Job Abandoned"
        message = "You left me alone in the cold and dark, I forgot who I was. Your job has been abandoned."
        notify(job, title, message)
        raise utils.RipperException("Manual mode: Timed out waiting for user input")

    if job.title_manual:
        logging.info("Manual override found.  Overriding auto identification values.")
        utils.database_updater({"hasnicetitle": True, "updated": True}, job)
    utils.database_updater({"status": JobState.VIDEO_RIPPING.value}, job)


def wait_for_manual_start(job, wait_minutes: int = 30, poll_seconds: int = 15) -> bool:
    """
    Wait for the user to submit their track selection (job.manual_start).

    The UI signals this process (Job.wake_for_manual_start) as soon as the user
    submits, so the rip starts right away. The database is also re-checked every
    poll_seconds in case that signal never arrives.

    Parameters:
        job (Job): the job waiting on the user
        wait_minutes: how long to wait before giving up
        poll_seconds: longest time between database checks

    Returns:
        bool: True if the user submitted in time, otherwise False

    Notes:
        - A reminder is sent every 5 minutes.
        - A final notification is sent when one minute is left, warning of potential
          cancellation.
    """
    title = "Manual Mode Activated!"
    message = f"ARM has taken it's hands off the wheels. You have {wait_minutes} minutes to set the job."
    notify(job, title, message)

    title = "Waiting for input on job!"
    deadline = monotonic() + wait_minutes * 60
    # Minutes-left marks to send a reminder at
    reminders = list(range(wait_minutes - 5, 0, -5)) + [1]
    # Block the wake signal so one arriving outside sigtimedwait() stays pending
    # (and is picked up by the next call) rather than being handled and lost
    wake_signals = {MANUAL_START_SIGNAL}
    signal.pthread_sigmask(signal.SIG_BLOCK, wake_signals)
    try:
        while True:
            db.session.refresh(job)
            remaining = deadline - monotonic()
            logging.debug(f"Wait time logging: [{remaining:.0f}]s left - Ready: [{job.manual_start}]")
            if job.manual_start:
                notify(job, "The Wait is Over", "Thanks for not forgetting me, I am now processing your job.")
                return True
            if remaining <= 0:
                return False

            while reminders and remaining <= reminders[0] * 60:
                minutes_left = reminders.pop(0)
                if minutes_left == 1:
                    body = "ARM is about to cancel this job!!! You have less than 1 minute left!"
                else:
                    body = f"Don't forget me, I need your help to continue doing ARM things!. " \
                           f"You have {minutes_left} minutes."
                notify(job, title, body)

            until_next_reminder = remaining - reminders[0] * 60 if reminders else remaining
            signal.sigtimedwait(wake_signals, min(until_next_reminder, poll_seconds))
    finally:
        signal.pthread_sigmask(signal.SIG_UNBLOCK, wake_signals)
